version: '3'
#docker container run --rm -it -p 8080:80 --name scriptsjs -v $PWD:/usr/share/nginx/html nginx
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8085:80'
    volumes:
      - '.:/var/www/html'
    
